# Generated by Django 5.0.2 on 2024-03-24 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
