# Generated by Django 5.0.2 on 2024-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='hotels.amenity'),
        ),
    ]
