# Generated by Django 5.0.2 on 2024-03-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=1023, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_system.image'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_system.image'),
        ),
    ]
