# Generated by Django 5.0.2 on 2024-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_image_hotel_image_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
