# Generated by Django 5.0.2 on 2024-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0003_amenity_facility_roomtype_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_price',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
